#!/usr/bin/env bash
# This script displays a list of currently running processes

# Header line
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Retrieve process information using ps command and format the output
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | head -n 51
