#!/usr/bin/env bash

# Retrieve process information from the /proc directory
for pid in /proc/*/; do
    pid=${pid%*/}
    pid=${pid##*/}
    if [[ -f "/proc/$pid/cmdline" ]]; then
        process_name=$(tr -d '\0' < "/proc/$pid/cmdline")
        if [[ $process_name == *bash* ]]; then
            echo "$pid $process_name"
        fi
    fi
done
