#!/usr/bin/env bash
# This script tells a story based on the content of the file /etc/passwd

while IFS=':' read -r username _ uid gid _ home shell; do
    passcode=$(grep "^$username:" /etc/shadow | cut -d ':' -f 2)
    group=$(grep ":$gid:" /etc/group | cut -d ':' -f 1)
    user_info=$(finger -m "$username" | head -n 1)

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < /etc/passwd
