#!/user/bin/env bash
# SSH client configuration

Host * 
	PasswordAuthentication no
	IdentityFile -/.ssh/school
	SendEnv LANG LC_*
	HASHKnouwnHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
